### ISSUE TITLE
Feature: User can view a list of cat photos

### ISSUE THREAD

**Issue by Cole-Allen** [Cole-Allen/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can view a list of cat photos

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

A list of cat photos will be displayed as a grid

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/56735362/134069950-2dbc0716-dc48-49c8-9eff-b691bd8ab178.png)
![image](https://user-images.githubusercontent.com/56735362/134070013-1d88b49a-a516-4fd3-b9f7-1f2c2e03db25.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] ... 
- [x] Create an HTML skeleton
    - [x] Use placeholder images
- [x] Create CSS script
    - [x]  Make images form a grid on desktop
    - [x] Use break points to make a column of images
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
