### ISSUE TITLE
Feature: User can enlarge a photo

### ISSUE THREAD

**Issue by Cole-Allen** [Cole-Allen/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can enlarge a photo by selecting it

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Selecting an image will bring up a modal showing more options and enlarging the image

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/56735362/134079695-39be3e41-03a4-470f-ad10-58a51f6eae56.png)
![image](https://user-images.githubusercontent.com/56735362/134079725-8021f335-3d7d-4e93-b408-5d925231df76.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] ... 
- [x] Create a modal
- [x] create a hidden class that hides anything attached to it
- [x] Create layout for enlarging an image
- [x] add buttons for future use
- [x] Enable closing the modal
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
