### ISSUE TITLE
Feature: User can add photos to their favorites and view them

### ISSUE THREAD

**Issue by Cole-Allen** [Cole-Allen/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can select an image to be apart of their favorites, that way they can reference them later

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Clicking on the favorite button (heart) will add that image to their favorites. Selecting the favorites tab at the top will show all their favorited images.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/56735362/134080157-641cc499-42dc-4976-8d0c-923413db0415.png)
![image](https://user-images.githubusercontent.com/56735362/134080164-ca9950d3-a1b1-41e3-a63b-0114029ee075.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] ... 
- [x] Add favorite button on images
- [x] Listen for clicks on the button
- [x] Store the image in a data object
- [x] Show confirmation of favoriting
- [x] Add a view for favorites
- [x] Switch views when clicking on the favorite tab
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
