### ISSUE TITLE
Feature: User can choose an image to edit into a meme

### ISSUE THREAD

**Issue by Cole-Allen** [Cole-Allen/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can choose an image they like to put text into the top and bottom of the image

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Clicking on the edit icon, opens it in a meme editor view, then you can type in text for the top and bottom text, then download the meme.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/56735362/134080736-720c8d5f-d2f6-446f-8832-9d150574bc31.png)
![image](https://user-images.githubusercontent.com/56735362/134080749-a8d09205-34d1-4db2-a105-a75657c6528a.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] ... 
- [x] Create a meme view
- [x] Prepopulate the meme layout with the selected image
- [x] Put text as an overlay of the image
- [ ] Save to computer after hitting save
- [x] Stay on the same page incase user wants to edit it some more
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
