### ISSUE TITLE
Feature: User can switch between light mode and dark mode

### ISSUE THREAD

**Issue by Cole-Allen** [Cole-Allen/ajax-project#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

user can toggle a switch to turn on and off dark mode

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Clicking on a switch on the top will change the background color from a light color to a dark color

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/56735362/135002829-6891126e-1ebb-4dff-9b31-a3867ada6772.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] ... 
- [ ] ...
- [x] Create a boolean that's saved to local storage so that the browser remembers the preferred mode
- [x] Add a switch at the top that will switch the background of the page and the look of the switch
- [x] Make sure the transition is smooth
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
